export const STAT_DEFINITIONS: Readonly<Record<string, string>> = {
  AVG: 'Batting Average. Hits divided by at-bats: H ÷ AB.',
  OPS: 'On-Base Plus Slugging. The sum of on-base percentage and slugging percentage: OBP + SLG.',
  OBP: 'On-Base Percentage. How often a hitter reaches base via a hit, walk, or hit-by-pitch, calculated as (H + BB + HBP) ÷ (AB + BB + HBP + SF).',
  SLG: 'Slugging Percentage. Total bases divided by at-bats, giving progressively more credit for doubles, triples, and home runs.',
  BsR: 'Base Running Runs. A season-level FanGraphs metric measured in runs above or below average, combining stolen-base value with advancement and other baserunning plays. Higher values indicate more runs contributed on the bases.',
  wOBA: 'Weighted On-Base Average. Overall offensive production measured by weighting each outcome according to its actual run-scoring value.',
  'wRC+': 'Weighted Runs Created Plus. Park- and league-adjusted offensive production where 100 is league average; 120 is approximately 20% better than average.',
  'BB%': 'Walk Percentage. The percentage of plate appearances that result in a walk: BB ÷ PA.',
  'K%': 'Strikeout Percentage. The percentage of plate appearances that result in a strikeout: K ÷ PA. Lower is generally better for hitters.',
  'BB/K': 'Walk-to-Strikeout Ratio. Walks divided by strikeouts: BB ÷ K. Higher values indicate more walks relative to strikeouts.',
  'O-Swing%': 'Chase Percentage. The percentage of pitches outside the strike zone at which the hitter swings: swings outside the zone ÷ pitches outside the zone.',
  'Contact%': 'Contact Percentage. The percentage of all swings on which the hitter makes contact: pitches contacted ÷ swings.',
  'CSW%': 'Called Strikes + Whiffs Percentage. The percentage of pitches that result in a called strike or swinging strike. Lower is generally better for hitters.',
  EV: 'Average Exit Velocity. The average speed, in miles per hour, at which the hitter’s batted balls leave the bat.',
  SprintSpeed: 'Sprint Speed. Statcast’s foot-speed metric in feet per second, based on a player’s fastest one-second window on qualifying competitive runs.',
  'Barrel%': 'Barrel Percentage. The percentage of batted balls with an especially favorable combination of exit velocity and launch angle associated with elite production.',
  'HardHit%': 'Hard-Hit Percentage. The percentage of batted balls hit at an exit velocity of 95 mph or greater.',
  xBA: 'Expected Batting Average. Estimates batting average from the probability that batted balls become hits, primarily using exit velocity and launch angle.',
  xSLG: 'Expected Slugging Percentage. Estimates slugging production from the quality of contact and probabilities derived from comparable batted balls.',
  xwOBA: 'Expected Weighted On-Base Average. Evaluates batted balls using exit velocity and launch angle—and Sprint Speed on certain balls—along with walks, strikeouts, and hit-by-pitches.',
  'LD%': 'Line-Drive Percentage. The percentage of balls in play classified as line drives: LD ÷ BIP.',
  'GB%': 'Ground-Ball Percentage. The percentage of balls in play classified as ground balls: GB ÷ BIP.',
  'FB%': 'Fly-Ball Percentage. The percentage of balls in play classified as fly balls: FB ÷ BIP.',
  'Pull%': 'Pull Percentage. The percentage of a hitter’s batted balls hit to his pull side.',
  'Cent%': 'Center Percentage. The percentage of a hitter’s batted balls hit to the middle of the field.',
  'Oppo%': 'Opposite-Field Percentage. The percentage of a hitter’s batted balls hit to the opposite field.',
  'Hard%': 'FanGraphs Hard-Contact Percentage. The percentage of the hitter’s batted balls classified as hard contact.',
}
